### ISSUE TITLE
credential validation has failed

### ISSUE THREAD

**Issue by fahhadalsubaie** [EQP-Solutions/OdooAddons#19]
Hello guys, 

After configuring the master password in the configuration tab & adding a new server, every time I add a new record, I get this error message:

`The Credential Validation failed. Error: The credential validation has failed. Please update the Database Management Master Password in the configuration section of this module.`

I'm 100% sure that I've used the correct master password, and I also went to the conf file copied it, and pasted it directly to make sure it's correctly configured, yet I get this error.

#18

**Comment by Esteban-Quevedo** [comment]
> Hello guys,
> 
> After configuring the master password in the configuration tab & adding a new server, every time I add a new record, I get this error message:
> 
> `The Credential Validation failed. Error: The credential validation has failed. Please update the Database Management Master Password in the configuration section of this module.`
> 
> I'm 100% sure that I've used the correct master password, and I also went to the conf file copied it, and pasted it directly to make sure it's correctly configured, yet I get this error.
> 
> #18

Hello @fahhadalsubaie,

I sincerely apologize for any inconvenience caused band the delayed response. Are you still encountering the error with the module? 
Could you please provide some details on how you are currently running Odoo? 
Are you utilizing Docker by any chance?

Thank you for your patience and cooperation.

Best regards,
